name: GitHub Actions Demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      ".github/**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0" 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente:'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: "echo EVENTO NOMBRE: ${{ github.event_name }}"
      - run: "echo ${{ github.ref }}"
      - uses: actions/checkout@v4
      - name: List files in the repository
      - run: "ls"
  Test:
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - run: "echo TESTING ..."
